Django==1.11
django-braces==1.9.0
requests==2.7.0
#fieldbook_py # it gives "RuntimeError: maximum recursion depth exceeded"